#ifndef FAST_LDA_ERROR_CODE_H_
#define FAST_LDA_ERROR_CODE_H_

#define INVALID_CALL -1
#define INVALID_NUM_ITERATIONS -11
#define INVALID_NUM_TOPICS -12
#define INVALID_NUM_THREADS -13
#define CANNOT_OPEN_FILE -20
#define OUT_OF_MEMORY -100

#endif  // FAST_LDA_ERROR_CODE_H_

